project:
  type: website

website:
  title: "Aaron Wenger"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Papers"
        href: papers.qmd
      - text: "Presentations"
        href: presentations.qmd
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
execute: 
  freeze: auto

bibliography: blog.bib



